apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: data
  name: data
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: data
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: data
    spec:
      volumes:
        - name: archLinux1984-assignment5
          persistentVolumeClaim:
            claimName:archLinux1984-assignment5
      containers:
      - env:
          - name: MYSQL_ALLOW_EMPTY_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: MYSQL_ALLOW_EMPTY_PASSWORD
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: MYSQL_DATABASE
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: MYSQL_PASSWORD
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: MYSQL_ROOT_PASSWORD
        image: archLinux1984/quotes-data:v1
        name: data
        ports:
        - containerPort: 3306
        volumeMounts:
        - mountPath: "/var/lib/mysql"
          subPath: mysql
          name: archLinux1984-assignment5
        resources: {}
      restartPolicy: Always
status: {}
